version: "3.9"

services:
  postgres:
    container_name: postgres_db
    image: postgres:15.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my-password
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    restart: on-failure



  keycloak:
    container_name: keycloak_docker
    image: quay.io/keycloak/keycloak:24.0.4
    command: -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: my-password
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: ALL
      KC_LOGL_EVEL: ALL
      ROOT_LOGLEVEL: ALL
      KC_PROXY: edge
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8090:8080
    restart: on-failure



volumes:
  postgres-db:
    driver: local